site_name: 'NCRP Documentation'
site_description: 'Welcome to the NCRP documentation'
site_author: 'NCRP'
site_url: 'https://docs.northcoastrp.net'
copyright: 'Copyright © 2021 NCRP'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc
  - footnotes

plugins:
    - search

nav:
  - Home: 'index.md'
  - Get Started: 'start.md'
  - Scripts:
    - Vmenu: 'scripts/vmenu.md'
  - Commands:
    - SASO: 'cmds/sheriff.md'
    - SAFR: 'cmds/fire.md'
    - CIV: 'cmds/civ.md'

