version: 2
jobs:
<<<<<<< Updated upstream
  build:
=======
  test:
>>>>>>> Stashed changes
    docker:
      - image: python:3.9
    steps:
      - checkout
<<<<<<< Updated upstream
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: |
            . venv/bin/activate
            mkdocs build
  deploy:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: |
            . venv/bin/activate
            mkdocs build
=======
      - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
      - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt

  docs-deploy:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
      - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
>>>>>>> Stashed changes
      - add_ssh_keys:
          fingerprints:
              - "5d:a4:90:70:8d:45:7c:ff:06:71:48:82:dc:be:d6:02"
      - run:
<<<<<<< Updated upstream
          name: Deploy
          command: |
            . venv/bin/activate
            git config user.email 25397933+Tslimshady99@users.noreply.github.com
            mkdocs gh-deploy
=======
          name: Deploy docs
          command: |
            git config user.email 25397933+Tslimshady99@users.noreply.github.com
            python3 -m mkdocs gh-deploy
>>>>>>> Stashed changes
workflows:
  version: 2
  gh-pages:
    jobs:
<<<<<<< Updated upstream
      - build
      - deploy:
=======
      - test
      - docs-deploy:
>>>>>>> Stashed changes
          filters:
            branches:
              only: master