version: 2
jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: |
            . venv/bin/activate
            mkdocs build
  deploy:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: |
            . venv/bin/activate
            mkdocs build
      - add_ssh_keys:
          fingerprints:
              - "5d:a4:90:70:8d:45:7c:ff:06:71:48:82:dc:be:d6:02"
      - run:
          name: Deploy
          command: |
            . venv/bin/activate
            git config user.email 25397933+Tslimshady99@users.noreply.github.com
            mkdocs gh-deploy
workflows:
  version: 2
  gh-pages:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master